server:
  port: ${SERVER_PORT:3000}

spring:
  config:
    import: optional:file:.env[.properties]
  security:
    jwt:
      secret: ${JWT_SECRET}
      expirationMs: ${JWT_EXPIRATION_MS:86400000}
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2000/eureka
  instance:
    prefer-ip-address: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
