server:
  port: ${SERVER_PORT}

spring:
  security:
    jwt:
      secret: ${JWT_SECRET}
      expirationMs: ${JWT_EXPIRATION_MS:86400000}
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
            - Path=/api/v1/restaurants/**
          filters:
            - name: CircuitBreaker
              args:
                name: restaurantServiceCircuitBreaker
                fallbackUri: forward:/restaurant-fallback
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
eureka:
  client:
    serviceUrl:
      defaultZone: ${SPRING_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
  instance:
    prefer-ip-address: true

resilience4j:
  circuitBreaker:
    instances:
      restaurantServiceCircuitBreaker:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
