server:
  port: ${SERVER_PORT}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
eureka:
  client:
    service-url:
      defaultZone: ${SPRING_EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, env, prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.tool.hbm2ddl: debug
