server:
  port: ${SERVER_PORT:4000}

spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:2000/eureka
  instance:
    prefer-ip-address: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
